
//create route
//read all the users
//read a user by id
//update a user by id
//delete a user by id

###
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"vivek",
    "email":"vivek@gmail.com",
    "dateOfBirth":"2000-09-12",
    "mobileNumber":11111111111
}

###
GET http://localhost:4000/user-api/users

###
GET http://localhost:4000/user-api/users/69a69c1cab32b2d98e0ec033

###
DELETE   http://localhost:4000/user-api/users/69a69c1cab32b2d98e0ec033

###
PATCH  http://localhost:4000/user-api/users/69a69c1cab32b2d98e0ec033


