###
GET http://127.0.0.1:4001/userApi/users

### read user by objectid
GET http://127.0.0.1:4001/userApi/users/697dbc20f001ae8d4da01722

###
POST http://127.0.0.1:4001/userApi/users
Content-Type: application/json

{
  "username": "revanh",
  "password": "revanth",
  "age": 21
}

### update user by objectid
PUT http://127.0.0.1:4001/userApi/users/697dbc20f001ae8d4da01722
Content-Type: application/json

{
  "username": "revanh",
  "password": "revanth",
  "age": 17
}

### delete user by objectid
DELETE http://127.0.0.1:4001/userApi/users/697dc61961e791ec25cdfed0


### Get all products
GET http://127.0.0.1:4001/productApi/products 

### read product by objectid
GET http://127.0.0.1:4001/productApi/products/697dd3418c99fe5b27ce4902

### Create product
POST http://127.0.0.1:4001/productApi/products
Content-Type: application/json

{
    "pid":100,
    "productName": "mobile",
    "price": 50000
}


###update the existing product
PUT http://localhost:4001/productApi/products/697f847d901d48156d1cd935
Content-Type: application/json

{
    "price":190000
}
